ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo_lists/', include('todo_lists.urls'))
]

todo_lists/urls.py
from django.urls import path
from . import views


app_name = 'todo_lists'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

todo_lists/models.py
from django.db import models


class Todo(models.Model):
    content = models.TextField()

    def __str__(self):
        return f'{self.pk}. {self.content}'

todo_lists/views.py
from django.shortcuts import render, redirect
from .models import Todo



def index(request):

    todo = Todo.objects.all()

    context = {
        'todo': todo,
    }
    return render(request, 'todo_lists/index.html', context)


def new(request):
    return render(request, 'todo_lists/new.html')



def create(requset):
    
    content = requset.POST.get('content')
    todo = Todo(content=content)
    todo.save()

    return redirect('todo_lists:index')


def delete(request, pk):

    todo = Todo.objects.get(pk=pk)
    todo.delete()
    
    return redirect('todo_lists:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>

  {% block content %}
  {% endblock content %}
  
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

todo_lists/templates/todo_lists/create.html
{% extends 'base.html' %}

{% block content %}

작성 완료


{% endblock content %}

todo_lists/templates/todo_lists/delete.html
{% extends 'base.html' %}

{% block content %}
삭제 페이지

{% endblock content %}

todo_lists/templates/todo_lists/index.html
{% extends 'base.html' %}

{% block content %}
<header class="m-3">
  <h1 class="fw-bold d-inline ">To-do List</h1>
  <h4 class="d-inline mx-3">with Django</h4>
  <hr>
</header>

<section class="m-5">
    {% for list in todo %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="form-check m-3">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          {{ list.pk }}. {{ list.content }}
        </label>
      </div>
      <button type="button" class="btn btn-danger">
        <a href="{% url 'todo_lists:delete' list.pk %}" class="text-decoration-none" style="color:white;">Del</a>
      </button>
    </div>
    <hr>
    {% endfor %}
</section>


{% endblock content %}

todo_lists/templates/todo_lists/new.html
{% extends 'base.html' %}

{% block content %}
<header class="m-3">
  <h1 class="fw-bold d-inline ">To-do List</h1>
  <h4 class="d-inline mx-3">with Django</h4>
  <hr>
</header>

<section class="m-5">
  <form action="{% url 'todo_lists:create' %}" method="POST">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="메모할 내용을 적어주세요" aria-label="Recipient's username" aria-describedby="button-addon2" name="content">
      <button class="btn btn-outline-secondary">메모하기!</button>
    </div>
  </form>
</section>


{% endblock content %}